services:
  base-app:
    extends:
      file: ../base-app/docker-compose.yml
      service: base-app
  
  base-app-db:
    extends:
      file: ../base-app/docker-compose.yml
      service: base-app-db
  
  base-app-phpmyadmin:
    extends: 
      file: ../base-app/docker-compose.yml
      service: base-app-phpmyadmin

  premium-rest-postgres:
    extends:
      file: ../premium-rest/docker-compose.yml
      service: premium-rest-postgres
    
  premium-rest-pgadmin:
    extends:
      file: ../premium-rest/docker-compose.yml
      service: premium-rest-pgadmin

  premium-rest-api:
    extends:
      file: ../premium-rest/docker-compose.yml
      service: prisma-postgres-api

  soap-mysql:
    extends:
      file: ../premium-soap/docker-compose.yml
      service: soap-mysql
  
  soap:
    extends:
      file: ../premium-soap/docker-compose.yml
      service: soap
  
  soap-phpmyadmin:
    extends:
      file: ../premium-soap/docker-compose.yml
      service: soap-phpmyadmin

  react:
    extends:
      file: ../premium-app/docker-compose.yml
      service: react

volumes:
  mysql-data:
  postgres-data:
  pgadmin-data: