services:
  base-app:
    extends:
      file: ../base-app/docker-compose.yml
      service: base-app
  
  base-app-db:
    extends:
      file: ../base-app/docker-compose.yml
      service: base-app-db
  
  base-app-phpmyadmin:
    extends: 
      file: ../base-app/docker-compose.yml
      service: base-app-phpmyadmin

  premium-rest-postgres:
    extends:
      file: ../premium-rest/docker-compose.yml
      service: premium-rest-postgres
    
  premium-rest-pgadmin:
    extends:
      file: ../premium-rest/docker-compose.yml
      service: premium-rest-pgadmin

  premium-rest-api:
    extends:
      file: ../premium-rest/docker-compose.yml
      service: prisma-postgres-api

volumes:
  postgres-data:
  pgadmin-data: